
@url = http://localhost:3000

###

// -----------------
// U S E R
// -----------------

// Register
POST {{url}}/user/register
Content-Type:application/json

{
	"username":  "Icaruk",
	"email": "asd@asd.com",
	"password":  "1234",
	"secretQuestion": "como se llamaba tu perro?",
	"secretAnswer": "toby",
	"phone": "647123456",
	"billing": {
		"address": "c/ Falsa, 123",
		"country": "Finland",
		"city": "Helsinki",
		"paypal": "vamosasermuuuuyricos@hotmail.com",
		"card": {
			"number": 123456789,
			"owner": "Adrian Apellido Apellido",
			"expireDate": [6, 22]
		}
		
	}
}
###


// Login
# @name resLogin
POST {{url}}/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###


@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}


// Logout
GET {{url}}/user/logout?token={{token}}
###


// Ver datos del usuario
GET {{url}}/user/{{userId}}?token={{token}}
###


// Delete user
DELETE {{url}}/user/delete/{{userId}}?token={{token}}
###



// -----------------
// R A T I N G
// -----------------


GET {{url}}/rating/all
###


POST {{url}}/rating/add
Content-Type:application/json

{
	"productId": "5de6863f19d26244901c5ec0",
	"raterId": "5de6863f19d26244901c7ec2",
	"ratedId": "5de6863f19d26244901c7ec2",
	"value": 1,
	"comment": "test 01"
}
###


POST {{url}}/rating/rated?id=5de6863f19d26244901c7ec2
###


// -----------------
// P R O D U C T
// -----------------

// Add
POST {{url}}/product/add
Content-Type:application/json

{
	"ownerId" : "",
	"category" : "",
	"imageUrl": ["asd.jpg","wwe.jpg"],
	"title":  "1234",
	"description": "647123456",
	"price": 0,
	"stock": "",
	"activeStock": "",
	"location" : "",
	"isActive": ""
}
###

// Edit
POST {{url}}/product/add
Content-Type:application/json

{
	"productId":  "",
	"imageUrl": ["asd.jpg","wwe.jpg"],
	"title":  "1234",
	"description": "647123456",
	"price": "c/ Falsa, 123",
	"stock": "",
	"activeStock": "",
	"isActive": ""
}
###

// Delete user
DELETE {{url}}/product/delete/productId?token={{token}}
###