
// Register
POST http://localhost:3000/user/register
Content-Type:application/json

{
	"username":  "Icaruk",
	"email": "asd@asd.com",
	"password":  "1234",
	"phone": "647123456",
	"address": "c/ Falsa, 123",
	"billing": {
		"cardNumber": 123456789,
		"cardOwner": "Adrian Apellido Apellido",
		"cardExpireDate": [6, 22]
	}
}
###


// Login
# @name resLogin
POST http://localhost:3000/user/login
Content-Type:application/json

{
	"username":  "Icaruk",
	"password":  "1234"
}
###


@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}


// Logout
GET http://localhost:3000/user/logout?token={{token}}
###


// Ver datos del usuario
GET http://localhost:3000/user/{{userId}}?token={{token}}
###


// Delete user
DELETE http://localhost:3000/user/delete/{{userId}}?token={{token}}
###



