
@url = http://localhost:3000

###

// -----------------
// U S E R
// -----------------

// Register
POST {{url}}/user/register
Content-Type:application/json

{
	"username":  "Jacinto",
	"email": "jac@jac",
	"password":  "1234",
	"secretQuestion": "como se llamaba tu perro?",
	"secretAnswer": "toby",
	"phone": "647123456",
	"userType": 0,
	"billing": {
		"address": "c/ Falsa, 123",
		"country": "Finland",
		"city": "Helsinki",
		"paypal": "jac@jac",
		"card": {
			"number": 33336666,
			"owner": "Jose Jacinto Javier",
			"expireDate": [6, 22]
		}
	}	
}
###


// Login
# @name resLogin
POST {{url}}/user/login
Content-Type:application/json

{
	"username":  "Jacinto",
	"password":  "2222"
}
###


@userId = {{resLogin.response.body.userId}}
@token = {{resLogin.response.body.token}}



// Logout
GET {{url}}/user/logout?token={{token}}
###


// Ver datos del usuario
GET {{url}}/user/{{userId}}?token={{token}}
###


// Delete user
DELETE {{url}}/user/delete/{{userId}}?token={{token}}
###

// Forgot Password
POST {{url}}/user/forgotPassword?token={{token}}
Content-Type:application/json

{
	"username": "Jacinto",
	"secretAnswer": "toby",
	"password":  "2222"
}
###


// -----------------
// R A T I N G
// -----------------


GET {{url}}/rating/all
###


POST {{url}}/rating/add
Content-Type:application/json

{
	"productId": "5de6863f19d26244901c5ec0",
	"raterId": "5de6863f19d26244901c7ec2",
	"ratedId": "5de6863f19d26244901c7ec2",
	"value": 1,
	"comment": "test 01"
}
###


POST {{url}}/rating/rated?id=5de6863f19d26244901c7ec2
###


// -----------------
// P R O D U C T
// -----------------

// Add
POST {{url}}/product/add?token={{token}}
Content-Type:application/json

{
	"ownerId" : "{{userId}}",
	"category" : "Informatica",
	"imageUrl": ["asd.jpg","wwe.jpg"],
	"title":  "1234",
	"description": "Es un super mega articulo fabuloso",
	"price": 666,
	"stock": 1000,
	"activeStock": 2000,
	"location" : "Valencia",
	"isActive": true
}
###

// Edit
POST {{url}}/product/edit?token={{token}}
Content-Type:application/json

{
	"productId":  "5de93163dc4bc910489ce0f2",
	"imageUrl": ["hahahahahahaasd.jpg","wwe.jpg"],
	"title":  "66677788888888888",
	"description": "sigue siendo mega bueno",
	"price": 444,
	"stock": 99,
	"activeStock": 5000,
	"isActive": false
}
###

// Delete product
DELETE {{url}}/product/delete?id=5de93163dc4bc910489ce0f2&token={{token}}
###

// Show all products
GET {{url}}/product/all
###

// Show best selling products
GET {{url}}/product/best?limit=10
###

// Show products of a certain Owner
GET {{url}}/product/getByOwner?ownerId=5de92b6b42933a3b3403ce96&token={{token}}
###

// Show products by Id
GET {{url}}/product/get?id=5de93163dc4bc910489ce0f2&token={{token}}
###

// Show products by Title
GET {{url}}/product/s?title=silla&token={{token}}
###
